const products = [
  { image: require('./assets/lap1.png'), category: 'Laptops' },
  { image: require('./assets/lap2.png'), category: 'Laptops' },
  { image: require('./assets/lap4.png'), category: 'Laptops' },
  { image: require('./assets/lap6.png'), category: 'Laptops' },
  { image: require('./assets/watch6.png'), category: 'Touch Watches' },
  { image: require('./assets/watch7.png'), category: 'Touch Watches' },
  { image: require('./assets/watch8.png'), category: 'Touch Watches' },
  { image: require('./assets/watch10.png'), category: 'Touch Watches' },
  { image: require('./assets/watch9.png'), category: 'Touch Watches' },
  { image: require('./assets/watch3.png'), category: 'Touch Watches' },
  { image: require('./assets/mob6.png'), category: 'Mobiles' },
  { image: require('./assets/mob1.png'), category: 'Mobiles' },
  { image: require('./assets/mob7.png'), category: 'Mobiles' },
  { image: require('./assets/mob8.png'), category: 'Mobiles' },
  { image: require('./assets/mob9.png'), category: 'Mobiles' },
  { image: require('./assets/tv1.png'), category: 'TV Screens' },
  { image: require('./assets/tv2.png'), category: 'TV Screens' },
  { image: require('./assets/tv4.png'), category: 'TV Screens' },
  { image: require('./assets/tv5.png'), category: 'TV Screens' },
  { image: require('./assets/tv6.png'), category: 'TV Screens' },
  { image: require('./assets/cam1.png'), category: 'Cameras' },
  { image: require('./assets/cam2.png'), category: 'Cameras' },
  { image: require('./assets/cam3.png'), category: 'Cameras' },
  { image: require('./assets/cam4.png'), category: 'Cameras' },
  { image: require('./assets/computer1.png'), category: 'Computers' },
  { image: require('./assets/computer2.png'), category: 'Computers' },
  { image: require('./assets/computer3.png'), category: 'Computers' },
  { image: require('./assets/computer4.png'), category: 'Computers' },
  { image: require('./assets/computer5.png'), category: 'Computers' },
  { image: require('./assets/computer6.png'), category: 'Computers' },
  { image: require('./assets/computer7.png'), category: 'Computers' }
];

export default products;